#2. datei (g)

global_path = ""
name = ""

own_path = "" #path fÃ¼r eingene datei
gue_path = "" #path fÃ¼r andere datei
path = ""


world.clearAll
world.setSize(101,29)
        world.setLeaf(11,6,true)
        world.setLeaf(12,6,true)
        world.setLeaf(10,5,true)
        world.setLeaf(10,4,true)
        world.setLeaf(12,4,true)
        world.setLeaf(10,3,true)
        world.setLeaf(11,2,true)
        world.setLeaf(12,2,true)
        world.setLeaf(13,2,true)
        world.setLeaf(13,4,true)
        world.setLeaf(13,5,true)
        world.setLeaf(13,6,true)
        world.setLeaf(15,6,true)
        world.setLeaf(16,6,true)
        world.setLeaf(17,6,true)
        world.setLeaf(15,5,true)
        world.setLeaf(15,4,true)
        world.setLeaf(16,4,true)
        world.setLeaf(17,4,true)
        world.setLeaf(15,3,true)
        world.setLeaf(15,2,true)
        world.setLeaf(16,2,true)
        world.setLeaf(17,2,true)
        world.setLeaf(20,6,true)
        world.setLeaf(21,6,true)
        world.setLeaf(19,5,true)
        world.setLeaf(19,4,true)
        world.setLeaf(21,4,true)
        world.setLeaf(19,3,true)
        world.setLeaf(20,2,true)
        world.setLeaf(21,2,true)
        world.setLeaf(22,2,true)
        world.setLeaf(22,4,true)
        world.setLeaf(22,5,true)
        world.setLeaf(22,6,true)
        world.setLeaf(24,6,true)
        world.setLeaf(25,6,true)
        world.setLeaf(26,6,true)
        world.setLeaf(24,5,true)
        world.setLeaf(24,4,true)
        world.setLeaf(25,4,true)
        world.setLeaf(26,4,true)
        world.setLeaf(24,3,true)
        world.setLeaf(24,2,true)
        world.setLeaf(25,2,true)
        world.setLeaf(26,2,true)
        world.setLeaf(28,6,true)
        world.setLeaf(28,5,true)
        world.setLeaf(28,4,true)
        world.setLeaf(28,3,true)
        world.setLeaf(28,2,true)
        world.setLeaf(29,3,true)
        world.setLeaf(30,4,true)
        world.setLeaf(31,5,true)
        world.setLeaf(32,6,true)
        world.setLeaf(32,5,true)
        world.setLeaf(32,4,true)
        world.setLeaf(32,3,true)
        world.setLeaf(32,2,true)
        world.setLeaf(34,6,true)
        world.setLeaf(35,6,true)
        world.setLeaf(36,6,true)
        world.setLeaf(37,5,true)
        world.setLeaf(36,4,true)
        world.setLeaf(35,4,true)
        world.setLeaf(34,3,true)
        world.setLeaf(35,2,true)
        world.setLeaf(36,2,true)
        world.setLeaf(37,2,true)
        world.setLeaf(39,6,true)
        world.setLeaf(39,5,true)
        world.setLeaf(39,4,true)
        world.setLeaf(40,4,true)
        world.setLeaf(39,3,true)
        world.setLeaf(39,2,true)
        world.setLeaf(40,2,true)
        world.setLeaf(41,2,true)
        world.setLeaf(42,3,true)
        world.setLeaf(41,4,true)
        world.setLeaf(44,6,true)
        world.setLeaf(44,5,true)
        world.setLeaf(44,4,true)
        world.setLeaf(44,3,true)
        world.setLeaf(44,2,true)
        world.setLeaf(46,6,true)
        world.setLeaf(47,6,true)
        world.setLeaf(48,6,true)
        world.setLeaf(46,5,true)
        world.setLeaf(46,4,true)
        world.setLeaf(47,4,true)
        world.setLeaf(48,4,true)
        world.setLeaf(46,3,true)
        world.setLeaf(46,2,true)
        world.setLeaf(47,2,true)
        world.setLeaf(48,2,true)
        world.setLeaf(50,6,true)
        world.setLeaf(51,6,true)
        world.setLeaf(52,6,true)
        world.setLeaf(50,5,true)
        world.setLeaf(50,4,true)
        world.setLeaf(50,3,true)
        world.setLeaf(50,2,true)
        world.setLeaf(54,6,true)
        world.setLeaf(55,6,true)
        world.setLeaf(56,6,true)
        world.setLeaf(54,5,true)
        world.setLeaf(54,4,true)
        world.setLeaf(55,4,true)
        world.setLeaf(56,4,true)
        world.setLeaf(54,3,true)
        world.setLeaf(54,2,true)
        world.setLeaf(55,2,true)
        world.setLeaf(56,2,true)
        world.setLeaf(58,6,true)
        world.setLeaf(58,5,true)
        world.setLeaf(58,4,true)
        world.setLeaf(59,4,true)
        world.setLeaf(58,3,true)
        world.setLeaf(58,2,true)
        world.setLeaf(59,2,true)
        world.setLeaf(60,2,true)
        world.setLeaf(61,3,true)
        world.setLeaf(60,4,true)
        world.setLeaf(60,5,true)
        world.setLeaf(61,6,true)
        world.setLeaf(68,6,true)
        world.setLeaf(67,5,true)
        world.setLeaf(67,4,true)
        world.setLeaf(66,3,true)
        world.setLeaf(66,2,true)
        world.setLeaf(70,2,true)
        world.setLeaf(70,3,true)
        world.setLeaf(69,4,true)
        world.setLeaf(69,5,true)
        world.setLeaf(72,6,true)
        world.setLeaf(73,6,true)
        world.setLeaf(74,6,true)
        world.setLeaf(72,5,true)
        world.setLeaf(72,4,true)
        world.setLeaf(73,4,true)
        world.setLeaf(74,4,true)
        world.setLeaf(72,3,true)
        world.setLeaf(72,2,true)
        world.setLeaf(73,2,true)
        world.setLeaf(74,2,true)
        world.setLeaf(76,6,true)
        world.setLeaf(76,5,true)
        world.setLeaf(76,4,true)
        world.setLeaf(77,4,true)
        world.setLeaf(76,3,true)
        world.setLeaf(76,2,true)
        world.setLeaf(77,2,true)
        world.setLeaf(78,2,true)
        world.setLeaf(79,3,true)
        world.setLeaf(78,4,true)
        world.setLeaf(78,5,true)
        world.setLeaf(79,6,true)
        world.setLeaf(81,6,true)
        world.setLeaf(82,6,true)
        world.setLeaf(83,6,true)
        world.setLeaf(84,5,true)
        world.setLeaf(83,4,true)
        world.setLeaf(82,4,true)
        world.setLeaf(81,3,true)
        world.setLeaf(82,2,true)
        world.setLeaf(83,2,true)
        world.setLeaf(84,2,true)
        world.setLeaf(86,6,true)
        world.setLeaf(86,5,true)
        world.setLeaf(86,4,true)
        world.setLeaf(86,3,true)
        world.setLeaf(86,2,true)
        world.setLeaf(89,6,true)
        world.setLeaf(90,6,true)
        world.setLeaf(88,5,true)
        world.setLeaf(88,4,true)
        world.setLeaf(88,3,true)
        world.setLeaf(89,2,true)
        world.setLeaf(90,2,true)
        world.setLeaf(91,3,true)
        world.setLeaf(91,4,true)
        world.setLeaf(91,5,true)
        world.setLeaf(93,6,true)
        world.setLeaf(93,5,true)
        world.setLeaf(93,4,true)
        world.setLeaf(93,3,true)
        world.setLeaf(93,2,true)
        world.setLeaf(94,3,true)
        world.setLeaf(95,4,true)
        world.setLeaf(96,5,true)
        world.setLeaf(97,6,true)
        world.setLeaf(97,5,true)
        world.setLeaf(97,4,true)
        world.setLeaf(97,3,true)
        world.setLeaf(97,2,true)
        world.setLeaf(99,5,true)
        world.setLeaf(99,3,true)
        world.setLeaf(2,13,true)
        world.setLeaf(3,13,true)
        world.setLeaf(4,13,true)
        world.setLeaf(1,12,true)
        world.setLeaf(1,11,true)
        world.setLeaf(1,10,true)
        world.setLeaf(2,9,true)
        world.setLeaf(3,9,true)
        world.setLeaf(4,9,true)
        world.setLeaf(5,10,true)
        world.setLeaf(5,11,true)
        world.setLeaf(5,12,true)
        world.setLeaf(11,13,true)
        world.setLeaf(10,12,true)
        world.setLeaf(10,11,true)
        world.setLeaf(10,10,true)
        world.setLeaf(11,9,true)
        world.setLeaf(12,9,true)
        world.setLeaf(13,10,true)
        world.setLeaf(13,12,true)
        world.setLeaf(12,13,true)
        world.setLeaf(15,13,true)
        world.setLeaf(15,12,true)
        world.setLeaf(15,11,true)
        world.setLeaf(16,11,true)
        world.setLeaf(15,10,true)
        world.setLeaf(15,9,true)
        world.setLeaf(18,9,true)
        world.setLeaf(18,10,true)
        world.setLeaf(18,11,true)
        world.setLeaf(17,11,true)
        world.setLeaf(18,12,true)
        world.setLeaf(18,13,true)
        world.setLeaf(20,13,true)
        world.setLeaf(20,12,true)
        world.setLeaf(20,11,true)
        world.setLeaf(21,11,true)
        world.setLeaf(20,10,true)
        world.setLeaf(21,9,true)
        world.setLeaf(22,9,true)
        world.setLeaf(23,10,true)
        world.setLeaf(23,11,true)
        world.setLeaf(22,11,true)
        world.setLeaf(23,12,true)
        world.setLeaf(23,13,true)
        world.setLeaf(27,13,true)
        world.setLeaf(27,12,true)
        world.setLeaf(27,11,true)
        world.setLeaf(27,10,true)
        world.setLeaf(27,9,true)
        world.setLeaf(26,9,true)
        world.setLeaf(25,9,true)
        world.setLeaf(28,9,true)
        world.setLeaf(29,9,true)
        world.setLeaf(2,20,true)
        world.setLeaf(3,20,true)
        world.setLeaf(4,20,true)
        world.setLeaf(1,19,true)
        world.setLeaf(1,18,true)
        world.setLeaf(1,17,true)
        world.setLeaf(2,16,true)
        world.setLeaf(3,16,true)
        world.setLeaf(4,16,true)
        world.setLeaf(5,17,true)
        world.setLeaf(5,18,true)
        world.setLeaf(5,19,true)
        world.setLeaf(10,20,true)
        world.setLeaf(10,19,true)
        world.setLeaf(10,18,true)
        world.setLeaf(10,17,true)
        world.setLeaf(10,16,true)
        world.setLeaf(13,16,true)
        world.setLeaf(12,17,true)
        world.setLeaf(11,18,true)
        world.setLeaf(12,19,true)
        world.setLeaf(13,20,true)
        world.setLeaf(15,20,true)
        world.setLeaf(15,19,true)
        world.setLeaf(15,18,true)
        world.setLeaf(16,18,true)
        world.setLeaf(15,17,true)
        world.setLeaf(16,16,true)
        world.setLeaf(17,16,true)
        world.setLeaf(18,17,true)
        world.setLeaf(18,18,true)
        world.setLeaf(17,18,true)
        world.setLeaf(18,19,true)
        world.setLeaf(18,20,true)
        world.setLeaf(20,20,true)
        world.setLeaf(20,19,true)
        world.setLeaf(20,18,true)
        world.setLeaf(21,18,true)
        world.setLeaf(20,17,true)
        world.setLeaf(20,16,true)
        world.setLeaf(21,16,true)
        world.setLeaf(22,16,true)
        world.setLeaf(23,17,true)
        world.setLeaf(22,18,true)
        world.setLeaf(22,19,true)
        world.setLeaf(23,20,true)
        world.setLeaf(25,20,true)
        world.setLeaf(25,19,true)
        world.setLeaf(25,18,true)
        world.setLeaf(26,18,true)
        world.setLeaf(25,17,true)
        world.setLeaf(26,16,true)
        world.setLeaf(27,16,true)
        world.setLeaf(28,17,true)
        world.setLeaf(28,18,true)
        world.setLeaf(27,18,true)
        world.setLeaf(28,19,true)
        world.setLeaf(28,20,true)
        world.setLeaf(30,20,true)
        world.setLeaf(31,20,true)
        world.setLeaf(32,20,true)
        world.setLeaf(33,19,true)
        world.setLeaf(32,18,true)
        world.setLeaf(31,18,true)
        world.setLeaf(30,17,true)
        world.setLeaf(31,16,true)
        world.setLeaf(32,16,true)
        world.setLeaf(33,16,true)
        world.setLeaf(39,20,true)
        world.setLeaf(41,20,true)
        world.setLeaf(42,19,true)
        world.setLeaf(40,19,true)
        world.setLeaf(38,19,true)
        world.setLeaf(38,18,true)
        world.setLeaf(38,17,true)
        world.setLeaf(38,16,true)
        world.setLeaf(42,16,true)
        world.setLeaf(42,17,true)
        world.setLeaf(42,18,true)
        world.setLeaf(44,20,true)
        world.setLeaf(45,20,true)
        world.setLeaf(46,20,true)
        world.setLeaf(44,19,true)
        world.setLeaf(44,18,true)
        world.setLeaf(45,18,true)
        world.setLeaf(46,18,true)
        world.setLeaf(44,17,true)
        world.setLeaf(44,16,true)
        world.setLeaf(45,16,true)
        world.setLeaf(46,16,true)
        world.setLeaf(49,20,true)
        world.setLeaf(50,20,true)
        world.setLeaf(48,19,true)
        world.setLeaf(48,18,true)
        world.setLeaf(50,18,true)
        world.setLeaf(48,17,true)
        world.setLeaf(49,16,true)
        world.setLeaf(50,16,true)
        world.setLeaf(51,16,true)
        world.setLeaf(51,18,true)
        world.setLeaf(51,19,true)
        world.setLeaf(51,20,true)
        world.setLeaf(2,27,true)
        world.setLeaf(3,27,true)
        world.setLeaf(4,27,true)
        world.setLeaf(1,26,true)
        world.setLeaf(1,25,true)
        world.setLeaf(1,24,true)
        world.setLeaf(2,23,true)
        world.setLeaf(3,23,true)
        world.setLeaf(4,23,true)
        world.setLeaf(5,24,true)
        world.setLeaf(5,25,true)
        world.setLeaf(5,26,true)
        world.setLeaf(10,27,true)
        world.setLeaf(10,26,true)
        world.setLeaf(10,25,true)
        world.setLeaf(10,24,true)
        world.setLeaf(10,23,true)
        world.setLeaf(11,24,true)
        world.setLeaf(12,25,true)
        world.setLeaf(13,24,true)
        world.setLeaf(14,23,true)
        world.setLeaf(14,24,true)
        world.setLeaf(14,25,true)
        world.setLeaf(14,26,true)
        world.setLeaf(14,27,true)
        world.setLeaf(16,27,true)
        world.setLeaf(16,26,true)
        world.setLeaf(16,25,true)
        world.setLeaf(17,25,true)
        world.setLeaf(16,24,true)
        world.setLeaf(17,23,true)
        world.setLeaf(18,23,true)
        world.setLeaf(19,24,true)
        world.setLeaf(19,25,true)
        world.setLeaf(18,25,true)
        world.setLeaf(19,26,true)
        world.setLeaf(19,27,true)
        world.setLeaf(21,27,true)
        world.setLeaf(21,26,true)
        world.setLeaf(21,25,true)
        world.setLeaf(21,24,true)
        world.setLeaf(21,23,true)
        world.setLeaf(23,27,true)
        world.setLeaf(24,27,true)
        world.setLeaf(25,27,true)
        world.setLeaf(23,26,true)
        world.setLeaf(23,25,true)
        world.setLeaf(23,24,true)
        world.setLeaf(23,23,true)
fa = ""
while fa == ""
  for hx in 2..4
    for hy in 10..12
      if world.isMushroom(hx,hy)
        fa = "chat"
      end
    end
  end
  for hx in 2..4
    for hy in 17..19
      if world.isMushroom(hx,hy)
        fa = "karas weg"
      end
    end
  end
  for hx in 2..4
    for hy in 24..26
      if world.isMushroom(hx,hy)
        fa = "mail"
      end
    end
  end
end
case fa
  when "chat"
    v7 = 0
    v8 = 1
    tools.showMessage("du kannst jetzt chaten")
    while true
      v3 = File.size(own_path)
      v6 = File.size(gue_path)
      if v3 == 0 
        if v8 == 0 and v6 == 0
          v1 = tools.stringInput("gieb die nachricht an den anderen computer ein")
          v2 = File.new(gue_path, "w+")
          v2.puts(v1)
          v2.rewind
          v7 = 0
          v8 = 1
        end
      else
        if v7 == 0
          v4 = File.open(own_path)
          v5 = v4.readline
          if v5.chomp == "-ende"
            tools.showMessage("chat wurde beendet beendet")
            abort
          end
          tools.showMessage(v5)
          v5 = File.new(own_path, "w+")
          v7 = 1
          v8 = 0
        end
      end
      tools.sleep(50)
      tools.checkState
    end
  when "karas weg"
    f = File.new(path, "w+")
    f.puts()
    f.rewind
    world.clearAll
    world.setSize(9,9)
    kara.setPosition(0,0)
    p = "00"
    w = tools.stringInput("gieb karas weg ein")
    w.each_byte do |y|
      case (y.chr)
        when "m"
          kara.move
        when "r"
          kara.turnRight
        when "l"
          kara.turnLeft
      end
      x = kara.getPosition.getX.to_i
      y = kara.getPosition.getY.to_i
      p = p + x.to_s + y.to_s
    end
    v = File.new(path, "w+")
    v.puts(p)
    v.rewind
  when "mail"
  while true
        world.clearAll
        world.setSize(51,36)
        world.setLeaf(10,6,true)
        world.setLeaf(10,5,true)
        world.setLeaf(10,4,true)
        world.setLeaf(10,3,true)
        world.setLeaf(10,2,true)
        world.setLeaf(11,3,true)
        world.setLeaf(12,4,true)
        world.setLeaf(13,3,true)
        world.setLeaf(14,2,true)
        world.setLeaf(14,3,true)
        world.setLeaf(14,4,true)
        world.setLeaf(14,5,true)
        world.setLeaf(14,6,true)
        world.setLeaf(16,6,true)
        world.setLeaf(16,5,true)
        world.setLeaf(16,4,true)
        world.setLeaf(17,4,true)
        world.setLeaf(16,3,true)
        world.setLeaf(17,2,true)
        world.setLeaf(18,2,true)
        world.setLeaf(19,3,true)
        world.setLeaf(19,4,true)
        world.setLeaf(18,4,true)
        world.setLeaf(19,5,true)
        world.setLeaf(19,6,true)
        world.setLeaf(21,6,true)
        world.setLeaf(21,5,true)
        world.setLeaf(21,4,true)
        world.setLeaf(21,3,true)
        world.setLeaf(21,2,true)
        world.setLeaf(23,6,true)
        world.setLeaf(24,6,true)
        world.setLeaf(25,6,true)
        world.setLeaf(23,5,true)
        world.setLeaf(23,4,true)
        world.setLeaf(23,3,true)
        world.setLeaf(23,2,true)
        world.setLeaf(2,13,true)
        world.setLeaf(3,13,true)
        world.setLeaf(4,13,true)
        world.setLeaf(1,12,true)
        world.setLeaf(1,11,true)
        world.setLeaf(1,10,true)
        world.setLeaf(2,9,true)
        world.setLeaf(3,9,true)
        world.setLeaf(4,9,true)
        world.setLeaf(5,10,true)
        world.setLeaf(5,11,true)
        world.setLeaf(5,12,true)
        world.setLeaf(10,13,true)
        world.setLeaf(11,13,true)
        world.setLeaf(12,13,true)
        world.setLeaf(10,12,true)
        world.setLeaf(10,11,true)
        world.setLeaf(10,10,true)
        world.setLeaf(10,9,true)
        world.setLeaf(14,13,true)
        world.setLeaf(15,13,true)
        world.setLeaf(16,13,true)
        world.setLeaf(14,12,true)
        world.setLeaf(14,11,true)
        world.setLeaf(15,11,true)
        world.setLeaf(16,11,true)
        world.setLeaf(14,10,true)
        world.setLeaf(14,9,true)
        world.setLeaf(15,9,true)
        world.setLeaf(16,9,true)
        world.setLeaf(18,13,true)
        world.setLeaf(19,13,true)
        world.setLeaf(20,13,true)
        world.setLeaf(21,12,true)
        world.setLeaf(20,11,true)
        world.setLeaf(19,11,true)
        world.setLeaf(18,10,true)
        world.setLeaf(19,9,true)
        world.setLeaf(20,9,true)
        world.setLeaf(21,9,true)
        world.setLeaf(23,13,true)
        world.setLeaf(24,13,true)
        world.setLeaf(25,13,true)
        world.setLeaf(23,12,true)
        world.setLeaf(23,11,true)
        world.setLeaf(24,11,true)
        world.setLeaf(25,11,true)
        world.setLeaf(23,10,true)
        world.setLeaf(23,9,true)
        world.setLeaf(24,9,true)
        world.setLeaf(25,9,true)
        world.setLeaf(27,13,true)
        world.setLeaf(27,12,true)
        world.setLeaf(27,11,true)
        world.setLeaf(27,10,true)
        world.setLeaf(27,9,true)
        world.setLeaf(28,10,true)
        world.setLeaf(29,11,true)
        world.setLeaf(30,12,true)
        world.setLeaf(31,13,true)
        world.setLeaf(31,12,true)
        world.setLeaf(31,11,true)
        world.setLeaf(31,10,true)
        world.setLeaf(31,9,true)
        world.setLeaf(2,20,true)
        world.setLeaf(3,20,true)
        world.setLeaf(4,20,true)
        world.setLeaf(1,19,true)
        world.setLeaf(1,18,true)
        world.setLeaf(1,17,true)
        world.setLeaf(2,16,true)
        world.setLeaf(3,16,true)
        world.setLeaf(4,16,true)
        world.setLeaf(5,17,true)
        world.setLeaf(5,18,true)
        world.setLeaf(5,19,true)
        world.setLeaf(10,20,true)
        world.setLeaf(11,20,true)
        world.setLeaf(12,20,true)
        world.setLeaf(13,19,true)
        world.setLeaf(12,18,true)
        world.setLeaf(11,18,true)
        world.setLeaf(10,17,true)
        world.setLeaf(11,16,true)
        world.setLeaf(12,16,true)
        world.setLeaf(13,16,true)
        world.setLeaf(16,20,true)
        world.setLeaf(15,19,true)
        world.setLeaf(15,18,true)
        world.setLeaf(15,17,true)
        world.setLeaf(16,16,true)
        world.setLeaf(17,16,true)
        world.setLeaf(18,17,true)
        world.setLeaf(18,19,true)
        world.setLeaf(17,20,true)
        world.setLeaf(20,20,true)
        world.setLeaf(20,19,true)
        world.setLeaf(20,18,true)
        world.setLeaf(21,18,true)
        world.setLeaf(20,17,true)
        world.setLeaf(20,16,true)
        world.setLeaf(23,16,true)
        world.setLeaf(23,17,true)
        world.setLeaf(23,18,true)
        world.setLeaf(22,18,true)
        world.setLeaf(23,19,true)
        world.setLeaf(23,20,true)
        world.setLeaf(25,20,true)
        world.setLeaf(25,19,true)
        world.setLeaf(25,18,true)
        world.setLeaf(26,18,true)
        world.setLeaf(25,17,true)
        world.setLeaf(25,16,true)
        world.setLeaf(26,16,true)
        world.setLeaf(27,16,true)
        world.setLeaf(28,17,true)
        world.setLeaf(27,18,true)
        world.setLeaf(27,19,true)
        world.setLeaf(28,20,true)
        world.setLeaf(30,20,true)
        world.setLeaf(31,20,true)
        world.setLeaf(32,20,true)
        world.setLeaf(30,19,true)
        world.setLeaf(30,18,true)
        world.setLeaf(31,18,true)
        world.setLeaf(32,18,true)
        world.setLeaf(30,17,true)
        world.setLeaf(30,16,true)
        world.setLeaf(31,16,true)
        world.setLeaf(32,16,true)
        world.setLeaf(34,20,true)
        world.setLeaf(34,19,true)
        world.setLeaf(34,18,true)
        world.setLeaf(34,17,true)
        world.setLeaf(34,16,true)
        world.setLeaf(36,20,true)
        world.setLeaf(37,20,true)
        world.setLeaf(36,19,true)
        world.setLeaf(36,18,true)
        world.setLeaf(37,18,true)
        world.setLeaf(36,17,true)
        world.setLeaf(36,16,true)
        world.setLeaf(37,16,true)
        world.setLeaf(38,16,true)
        world.setLeaf(39,17,true)
        world.setLeaf(38,18,true)
        world.setLeaf(39,19,true)
        world.setLeaf(38,20,true)
        world.setLeaf(41,20,true)
        world.setLeaf(42,20,true)
        world.setLeaf(43,20,true)
        world.setLeaf(41,19,true)
        world.setLeaf(41,18,true)
        world.setLeaf(42,18,true)
        world.setLeaf(43,18,true)
        world.setLeaf(41,17,true)
        world.setLeaf(41,16,true)
        world.setLeaf(42,16,true)
        world.setLeaf(43,16,true)
        world.setLeaf(45,20,true)
        world.setLeaf(45,19,true)
        world.setLeaf(45,18,true)
        world.setLeaf(45,17,true)
        world.setLeaf(45,16,true)
        world.setLeaf(46,17,true)
        world.setLeaf(47,18,true)
        world.setLeaf(48,19,true)
        world.setLeaf(49,20,true)
        world.setLeaf(49,19,true)
        world.setLeaf(49,18,true)
        world.setLeaf(49,17,true)
        world.setLeaf(49,16,true)
        world.setLeaf(2,27,true)
        world.setLeaf(3,27,true)
        world.setLeaf(4,27,true)
        world.setLeaf(1,26,true)
        world.setLeaf(1,25,true)
        world.setLeaf(1,24,true)
        world.setLeaf(2,23,true)
        world.setLeaf(3,23,true)
        world.setLeaf(4,23,true)
        world.setLeaf(5,24,true)
        world.setLeaf(5,25,true)
        world.setLeaf(5,26,true)
        world.setLeaf(10,27,true)
        world.setLeaf(11,27,true)
        world.setLeaf(12,27,true)
        world.setLeaf(10,26,true)
        world.setLeaf(10,25,true)
        world.setLeaf(10,24,true)
        world.setLeaf(10,23,true)
        world.setLeaf(15,27,true)
        world.setLeaf(16,27,true)
        world.setLeaf(14,26,true)
        world.setLeaf(14,25,true)
        world.setLeaf(14,24,true)
        world.setLeaf(14,22,true)
        world.setLeaf(15,23,true)
        world.setLeaf(16,23,true)
        world.setLeaf(17,22,true)
        world.setLeaf(17,24,true)
        world.setLeaf(17,25,true)
        world.setLeaf(17,26,true)
        world.setLeaf(19,27,true)
        world.setLeaf(20,27,true)
        world.setLeaf(21,27,true)
        world.setLeaf(22,26,true)
        world.setLeaf(21,25,true)
        world.setLeaf(20,25,true)
        world.setLeaf(19,24,true)
        world.setLeaf(20,23,true)
        world.setLeaf(21,23,true)
        world.setLeaf(22,23,true)
        world.setLeaf(25,27,true)
        world.setLeaf(24,26,true)
        world.setLeaf(24,25,true)
        world.setLeaf(24,24,true)
        world.setLeaf(25,23,true)
        world.setLeaf(26,23,true)
        world.setLeaf(27,24,true)
        world.setLeaf(27,26,true)
        world.setLeaf(26,27,true)
        world.setLeaf(29,27,true)
        world.setLeaf(29,26,true)
        world.setLeaf(29,25,true)
        world.setLeaf(30,25,true)
        world.setLeaf(29,24,true)
        world.setLeaf(29,23,true)
        world.setLeaf(32,23,true)
        world.setLeaf(32,24,true)
        world.setLeaf(32,25,true)
        world.setLeaf(31,25,true)
        world.setLeaf(32,26,true)
        world.setLeaf(32,27,true)
        world.setLeaf(34,27,true)
        world.setLeaf(35,27,true)
        world.setLeaf(36,27,true)
        world.setLeaf(34,26,true)
        world.setLeaf(34,25,true)
        world.setLeaf(35,25,true)
        world.setLeaf(36,25,true)
        world.setLeaf(34,24,true)
        world.setLeaf(34,23,true)
        world.setLeaf(35,23,true)
        world.setLeaf(36,23,true)
        world.setLeaf(38,27,true)
        world.setLeaf(38,26,true)
        world.setLeaf(38,25,true)
        world.setLeaf(38,24,true)
        world.setLeaf(38,23,true)
        world.setLeaf(39,24,true)
        world.setLeaf(40,25,true)
        world.setLeaf(41,26,true)
        world.setLeaf(42,27,true)
        world.setLeaf(42,26,true)
        world.setLeaf(42,25,true)
        world.setLeaf(42,24,true)
        world.setLeaf(42,23,true)
        world.setLeaf(2,34,true)
        world.setLeaf(3,34,true)
        world.setLeaf(4,34,true)
        world.setLeaf(1,33,true)
        world.setLeaf(1,32,true)
        world.setLeaf(1,31,true)
        world.setLeaf(2,30,true)
        world.setLeaf(3,30,true)
        world.setLeaf(4,30,true)
        world.setLeaf(5,31,true)
        world.setLeaf(5,32,true)
        world.setLeaf(5,33,true)
        world.setLeaf(10,34,true)
        world.setLeaf(11,34,true)
        world.setLeaf(12,34,true)
        world.setLeaf(10,33,true)
        world.setLeaf(10,32,true)
        world.setLeaf(11,32,true)
        world.setLeaf(12,32,true)
        world.setLeaf(10,31,true)
        world.setLeaf(10,30,true)
        world.setLeaf(11,30,true)
        world.setLeaf(12,30,true)
        world.setLeaf(14,34,true)
        world.setLeaf(14,33,true)
        world.setLeaf(14,32,true)
        world.setLeaf(14,31,true)
        world.setLeaf(14,30,true)
        world.setLeaf(15,31,true)
        world.setLeaf(16,32,true)
        world.setLeaf(17,33,true)
        world.setLeaf(18,34,true)
        world.setLeaf(18,33,true)
        world.setLeaf(18,32,true)
        world.setLeaf(18,31,true)
        world.setLeaf(18,30,true)
        world.setLeaf(20,34,true)
        world.setLeaf(21,34,true)
        world.setLeaf(22,34,true)
        world.setLeaf(20,33,true)
        world.setLeaf(20,32,true)
        world.setLeaf(20,31,true)
        world.setLeaf(20,30,true)
        world.setLeaf(21,30,true)
        world.setLeaf(22,30,true)
        world.setLeaf(23,31,true)
        world.setLeaf(23,32,true)
        world.setLeaf(23,33,true)
        world.setLeaf(25,34,true)
        world.setLeaf(26,34,true)
        world.setLeaf(27,34,true)
        world.setLeaf(25,33,true)
        world.setLeaf(25,32,true)
        world.setLeaf(26,32,true)
        world.setLeaf(27,32,true)
        world.setLeaf(25,31,true)
        world.setLeaf(25,30,true)
        world.setLeaf(26,30,true)
        world.setLeaf(27,30,true)
x = ""
while x == ""
  for hx in 2..4
    for hy in 10..12
      if world.isMushroom(hx,hy)
        x = "open"
      end
    end
  end
  for hx in 2..4
    for hy in 17..29
      if world.isMushroom(hx,hy)
        x = "write"
      end
    end
  end
  for hx in 2..4
    for hy in 24..26
      if world.isMushroom(hx,hy)
        x = "löschen"
      end
    end
  end
  for hx in 2..4
    for hy in 31..33
      if world.isMushroom(hx,hy)
        x = "ende"
      end
    end
  end
end
i = 0
world.clearAll
world.setSize(1,1)
case x
  when "write"
  e = 0
  k = ""
  namee = tools.stringInput("name des Empfengers")
  nachricht = tools.stringInput("gib die nachricht an den Empfenger ein")
  f = File.open(global_path+namee+"mail.txt")
  f.each do |line|
    e = e + 1
  end
  f.close
  f = File.open(global_path+namee+"mail.txt")
  for j in 1..e
    g = f.readline
    k = k+g+""
  end
  k = k+"("+Time.now.strftime("%A")+","+Time.now.day.to_s+"."+Time.now.month.to_s+"."+Time.now.year.to_s+" "+Time.now.hour.to_s+":"+Time.now.min.to_s+":"+Time.now.min.to_s+")"+" "+name+":  "+nachricht+"\r\n"
  ff = File.new(global_path+namee+"mail.txt","w+")
  ff.puts(k+"\r\n")
  #ff.rewind
  ff.close
  when "open"
    k = ""
    e = 0
    f = File.open(global_path+name+"mail.txt")
    f.each do |line|
      e = e + 1
    end
    f.close
    f = File.open(global_path+name+"mail.txt")
    for j in 1..e
      g = f.readline
      k = k+g+""#+"\r\n"
    end
    tools.showMessage(k.to_s)
  when "ende"
  abort
  when "löschen"
  File.new(global_path+name+"mail.txt","w+")
end
end
end
