def karas_welt(pack)
	kara = pack[0]
	tools = pack[1]
	world = pack[2]
	my_path = pack[3]
	menu = pack[4]
	global_path = pack[5]
	ip = pack[6]
	name = pack[7]
	app_path = pack[8]
    k = 0
	fspi = File.open(my_path + "karas_welt.txt")
	spieler1 = fspi.readline.to_i
	spieler2 = fspi.readline.to_i
	spieler3 = fspi.readline.to_i
	spieler4 = fspi.readline.to_i  
    sp = Input(kara,tools,world,app_path,menu,"wähle oder lösche einen Spieler","s","1/2/3/4/lösche 1/lösche 2/lösche 3/lösche 4","","")
    while k == 0
        dir = 0
        fspi = File.open(my_path + "karas_welt.txt")
	    spieler1 = fspi.readline.to_i
	    spieler2 = fspi.readline.to_i
	    spieler3 = fspi.readline.to_i
	    spieler4 = fspi.readline.to_i  
        case sp
			when "1"
				weltx = spieler1
			when "2"
				weltx = spieler2
			when "3"
				weltx = spieler3
			when "4"
				weltx = spieler4
			when "lösche 1"
				fspi = File.new(my_path + "karas_welt.txt", "w+")
				fspi.puts(1)
				fspi.puts(spieler2)
				fspi.puts(spieler3)
				fspi.puts(spieler4)
				fspi.rewind
				fspi.close
				k = 1
			when "lösche 2"
				fspi = File.new(my_path + "karas_welt.txt", "w+")
				fspi.puts(spieler1)
				fspi.puts(1)
				fspi.puts(spieler3)
				fspi.puts(spieler4)
				fspi.rewind
				fspi.close
				k = 1
			when "lösche 3"
				fspi = File.new(my_path + "karas_welt.txt", "w+")
				fspi.puts(spieler1)
				fspi.puts(spieler2)
				fspi.puts(1)
				fspi.puts(spieler4)
				fspi.rewind
				fspi.close
				k = 1
			when "lösche 4"
				fspi = File.new(my_path + "karas_welt.txt", "w+")
				fspi.puts(spieler1)
				fspi.puts(spieler2)
				fspi.puts(spieler3)
				fspi.puts(1)
				fspi.rewind
				fspi.close
				k = 1
			else
				k = 1
		end
        if k == 0
			case weltx
				when 1
					world.clearAll                      
					world.setSize(3 ,3)                
					kara.setPosition(1,1)
					kara.setDirection (2)
                    dir = 2
					world.setLeaf (1,1,true)
					world.setTree (0,0,true)
					world.setTree (0,1,true)
					world.setTree (0,2,true)
					world.setTree (1,0,true)
					world.setTree (2,0,true)
					world.setTree (2,1,true)
					world.setTree (2,2,true)
					world.setTree (1,2,true)
				when 2
					world.clearAll                      
					world.setSize(3 ,4)                
					kara.setPosition(1,1)
					kara.setDirection (2)
                    dir = 2
					world.setTree (0,0,true)
					world.setTree (0,1,true)
					world.setTree (0,2,true)
					world.setTree (0,3,true)
					world.setTree (1,0,true)
					world.setTree (2,0,true)
					world.setTree (2,1,true)
					world.setTree (2,2,true)
					world.setTree (2,3,true)
					world.setTree (1,3,true)
					world.setLeaf (1,2,true)
				when 3
					world.clearAll
					world.setSize(3,5)
					kara.setPosition(1,1)
					kara.setDirection (2)
                    dir = 2
					world.setTree (0,0,true)
					world.setTree (0,1,true)
					world.setTree (0,2,true)
					world.setTree (0,3,true)
					world.setTree (0,4,true)
					world.setTree (1,0,true)
					world.setTree (2,0,true)
					world.setTree (2,1,true)
					world.setTree (2,2,true)
					world.setTree (2,3,true)
					world.setTree (2,4,true)
					world.setTree (1,4,true)
					world.setLeaf (1,2,true)
					world.setMushroom (1,2,true)
				when 4
					world.clearAll
					world.setSize(4,3)
					kara.setPosition(1,1)
					kara.setDirection (2)
                    dir = 2
					world.setTree (0,0,true)
					world.setTree (1,0,true)
					world.setTree (2,0,true)
					world.setTree (3,0,true)
					world.setTree (3,1,true)
					world.setTree (3,2,true) 
					world.setTree (2,2,true)
					world.setTree (1,2,true)
					world.setTree (0,2,true)
					world.setTree (0,1,true)
					world.setLeaf (2,1,true)
				when 5
					world.clearAll
					world.setSize(5,5)
					kara.setPosition(1,1)
					kara.setDirection (3)
                    dir = 3
					world.setTree (0,0,true)
					world.setTree (1,0,true)
					world.setTree (2,0,true)
					world.setTree (3,0,true)
					world.setTree (3,2,true)
					world.setTree (1,2,true)
					world.setTree (0,2,true)
					world.setTree (0,1,true)
					world.setTree (4,0,true)
					world.setTree (4,2,true)
					world.setTree (4,1,true)
					world.setTree (4,3,true)
					world.setTree (4,4,true)
					world.setTree (3,4,true)
					world.setTree (2,4,true)
					world.setTree (1,4,true)
					world.setTree (0,4,true)
					world.setTree (0,3,true)
					world.setTree (1,3,true)
					world.setTree (3,3,true)
					world.setLeaf (2,2,true)
					world.setMushroom (2,2,true)
					world.setMushroom (2,1,true)
				when 6
					world.clearAll
					world.setSize(7,7)
					kara.setPosition(1,1)
					kara.setDirection (3)
                    dir = 3
					world.setTree (0,0,true)
					world.setTree (1,0,true)
					world.setTree (2,0,true)
					world.setTree (3,0,true)
					world.setTree (3,2,true)
					world.setTree (1,2,true)
					world.setTree (0,2,true)
					world.setTree (0,1,true)
					world.setTree (4,0,true)
					world.setTree (2,4,true)
					world.setTree (1,4,true)
					world.setTree (0,4,true)
					world.setTree (0,3,true)
					world.setTree (1,3,true)
					world.setTree (2,2,true)
					world.setTree (2,3,true)
					world.setTree (5,0,true)
					world.setTree (6,0,true)
					world.setTree (6,1,true)
					world.setTree (6,2,true)
					world.setTree (6,3,true)
					world.setTree (6,4,true)
					world.setTree (6,5,true)
					world.setTree (6,6,true)
					world.setTree (5,6,true)
					world.setTree (4,6,true)
					world.setTree (3,6,true)
					world.setTree (2,6,true)
					world.setTree (1,6,true)
					world.setTree (0,6,true)
					world.setTree (0,5,true)
					world.setTree (5,2,true)
					world.setTree (5,3,true)
					world.setTree (5,5,true)
					world.setTree (3,5,true)
					world.setTree (2,5,true)
					world.setTree (1,5,true)
					world.setLeaf (4,5,true)
					world.setMushroom (4,1,true)
					world.setMushroom (4,4,true)
				when 7
					world.clearAll
					world.setSize(9,7)
					kara.setPosition(5,1)
					kara.setDirection (3)
                    dir = 3
					world.setTree (0,0,true)
					world.setTree (1,0,true)
					world.setTree (2,0,true)
					world.setTree (3,0,true)
					world.setTree (4,0,true)
					world.setTree (5,0,true)
					world.setTree (6,0,true)
					world.setTree (7,0,true)
					world.setTree (8,0,true)
					world.setTree (8,1,true)
					world.setTree (0,1,true)
					world.setTree (1,1,true)
					world.setTree (2,1,true)
					world.setTree (1,2,true)
					world.setTree (0,2,true)
					world.setTree (2,2,true)
					world.setTree (0,3,true)
					world.setTree (0,4,true)
					world.setTree (0,5,true)
					world.setTree (0,6,true)
					world.setTree (1,6,true)
					world.setTree (2,6,true)
					world.setTree (3,6,true)
					world.setTree (4,6,true)
					world.setTree (5,6,true)
					world.setTree (6,6,true)
					world.setTree (7,6,true)
					world.setTree (8,6,true)
					world.setTree (8,5,true)
					world.setTree (8,4,true)
					world.setTree (8,3,true)
					world.setTree (8,2,true)
					world.setTree (4,1,true)
					world.setTree (6,2,true)
					world.setTree (6,3,true)
					world.setTree (5,3,true)
					world.setTree (7,5,true)
					world.setTree (6,5,true)
					world.setTree (5,5,true)
					world.setTree (2,4,true)
					world.setLeaf (4,3,true)
					world.setMushroom (4,3,true)
					world.setMushroom (4,4,true)
					world.setMushroom (4,2,true)
					world.setMushroom (3,2,true)
				when 8
					world.clearAll
					world.setSize(16,8)
					kara.setPosition(1,1)
					kara.setDirection (3)
                    dir = 3
					world.setTree (0,0,true)
					world.setTree (1,0,true)
					world.setTree (2,0,true)
					world.setTree (3,0,true)
					world.setTree (4,0,true)
					world.setTree (5,0,true)
					world.setTree (6,0,true)
					world.setTree (7,0,true)
					world.setTree (8,0,true)
					world.setTree (0,1,true)
					world.setTree (1,2,true)
					world.setTree (0,2,true)
					world.setTree (0,3,true)
					world.setTree (0,4,true)
					world.setTree (0,5,true)
					world.setTree (0,6,true)
					world.setTree (8,3,true)
					world.setTree (6,3,true)
					world.setTree (5,3,true)
					world.setTree (6,5,true)
					world.setTree (4,3,true)
					world.setTree (3,4,true)
					world.setTree (3,1,true)
					world.setTree (5,2,true)
					world.setTree (1,3,true)
					world.setTree (2,3,true)
					world.setTree (3,3,true)
					world.setTree (7,1,true)
					world.setTree (7,3,true)
					world.setTree (11,1,true)
					world.setTree (9,2,true)
					world.setTree (9,0,true)
					world.setTree (10,0,true)
					world.setTree (11,0,true)
					world.setTree (12,0,true)
					world.setTree (13,0,true)
					world.setTree (14,0,true)
					world.setTree (9,3,true)
					world.setTree (10,3,true)
					world.setTree (11,3,true)
					world.setTree (12,3,true)
					world.setTree (13,3,true)
					world.setTree (13,2,true)
					world.setTree (15,0,true)
					world.setTree (15,1,true)
					world.setTree (15,2,true)
					world.setTree (15,3,true)
					world.setTree (15,4,true)
					world.setTree (15,5,true)
					world.setTree (15,6,true)
					world.setTree (9,6,true)
					world.setTree (15,7,true)
					world.setTree (14,7,true)
					world.setTree (13,7,true)
					world.setTree (12,7,true)
					world.setTree (11,7,true)
					world.setTree (10,7,true)
					world.setTree (9,7,true)
					world.setTree (8,7,true)
					world.setTree (7,7,true)
					world.setTree (6,7,true)
					world.setTree (5,7,true)
					world.setTree (4,7,true)
					world.setTree (3,7,true)
					world.setTree (2,7,true)
					world.setTree (1,7,true)
					world.setTree (0,7,true)
					world.setTree (12,5,true)
					world.setTree (12,4,true)
					world.setTree (9,4,true)
					world.setTree (6,4,true)
					world.setMushroom (2,6,true)
					world.setMushroom (3,6,true)
					world.setMushroom (13,6,true)
					world.setMushroom (13,4,true)
					world.setMushroom (13,5,true)
					world.setMushroom (10,4,true)
					world.setMushroom (10,5,true)
					world.setMushroom (2,5,true)
					world.setMushroom (4,5,true)
					world.setLeaf (1,4,true)
				when 9
					world.clearAll
					world.setSize(16,8)
					kara.setPosition(1,1)
					kara.setDirection (3)
                    dir = 3
					world.setTree (0,0,true)
					world.setTree (1,0,true)
					world.setTree (2,0,true)
					world.setTree (3,0,true)
					world.setTree (4,0,true)
					world.setTree (5,0,true)
					world.setTree (6,0,true)
					world.setTree (7,0,true)
					world.setTree (8,0,true)
					world.setTree (0,1,true)
					world.setTree (1,2,true)
					world.setTree (0,2,true)
					world.setTree (0,3,true)
					world.setTree (0,4,true)
					world.setTree (0,5,true)
					world.setTree (0,6,true)
					world.setTree (5,2,true)
					world.setTree (2,3,true)
					world.setTree (7,3,true)
					world.setTree (9,2,true)
					world.setTree (9,0,true)
					world.setTree (10,0,true)
					world.setTree (11,0,true)
					world.setTree (12,0,true)
					world.setTree (13,0,true)
					world.setTree (14,0,true)
					world.setTree (11,3,true)
					world.setTree (13,2,true)
					world.setTree (15,0,true)
					world.setTree (15,1,true)
					world.setTree (15,2,true)
					world.setTree (15,3,true)
					world.setTree (15,4,true)
					world.setTree (15,5,true)
					world.setTree (15,6,true)
					world.setTree (15,7,true)
					world.setTree (14,7,true)
					world.setTree (13,7,true)
					world.setTree (12,7,true)
					world.setTree (11,7,true)
					world.setTree (10,7,true)
					world.setTree (9,7,true)
					world.setTree (8,7,true)
					world.setTree (7,7,true)
					world.setTree (6,7,true)
					world.setTree (5,7,true)
					world.setTree (4,7,true)
					world.setTree (3,7,true)
					world.setTree (2,7,true)
					world.setTree (1,7,true)
					world.setTree (0,7,true)
					world.setTree (12,4,true)
					world.setTree (9,4,true)
					world.setTree (6,4,true)
					world.setTree (13,4,true)
					world.setTree (10,4,true)
					world.setTree (4,4,true)
					world.setTree (14,2,true)
					world.setTree (2,2,true)
					world.setTree (4,2,true)
					world.setTree (5,1,true)
					world.setTree (2,4,true)
					world.setTree (2,5,true)
					world.setTree (3,5,true)
					world.setTree (4,5,true)
					world.setTree (5,4,true)
					world.setTree (7,4,true)
					world.setTree (7,2,true)
					world.setTree (9,1,true)
					world.setTree (8,4,true)
					world.setTree (11,2,true)
					world.setTree (11,4,true)
					world.setTree (13,1,true)
					world.setTree (14,1,true)
					world.setTree (12,6,true)
					world.setTree (9,5,true)
					world.setTree (6,6,true)
					world.setMushroom (3,1,true)
					world.setMushroom (3,3,true)
					world.setMushroom (9,6,true)
					world.setMushroom (12,5,true)
					world.setMushroom (14,4,true)
					world.setLeaf (1,3,true)
				when 10
					world.clearAll
					world.setSize(21,10)
					kara.setPosition(1,1)
					kara.setDirection (3)
                    dir = 3
					world.setTree (0,0,true)
					world.setTree (1,0,true)
					world.setTree (2,0,true)
					world.setTree (3,0,true)
					world.setTree (4,0,true)
					world.setTree (5,0,true)
					world.setTree (6,0,true)
					world.setTree (7,0,true)
					world.setTree (8,0,true)
					world.setTree (9,0,true)
					world.setTree (10,0,true)
					world.setTree (11,0,true)
					world.setTree (12,0,true)
					world.setTree (13,0,true)
					world.setTree (14,0,true)
					world.setTree (15,0,true)
					world.setTree (16,0,true)
					world.setTree (17,0,true)
					world.setTree (18,0,true)
					world.setTree (19,0,true)
					world.setTree (20,0,true)
					world.setTree (20,1,true)
					world.setTree (20,2,true)
					world.setTree (20,3,true)
					world.setTree (20,4,true)
					world.setTree (20,5,true)
					world.setTree (20,6,true)
					world.setTree (19,6,true)
					world.setTree (18,6,true)
					world.setTree (17,6,true)
					world.setTree (16,6,true)
					world.setTree (15,6,true)
					world.setTree (14,6,true)
					world.setTree (13,6,true)
					world.setTree (12,6,true)
					world.setTree (11,6,true)
					world.setTree (10,6,true)
					world.setTree (9,6,true)
					world.setTree (8,6,true)
					world.setTree (7,6,true)
					world.setTree (6,6,true)
					world.setTree (5,6,true)
					world.setTree (4,6,true)
					world.setTree (3,6,true)
					world.setTree (2,6,true)
					world.setTree (0,6,true)
					world.setTree (0,5,true)
					world.setTree (0,4,true)
					world.setTree (0,3,true)
					world.setTree (0,2,true)
					world.setTree (0,1,true)
					world.setTree (1,3,true)
					world.setTree (2,3,true)
					world.setTree (4,4,true)
					world.setTree (8,4,true)
					world.setTree (12,4,true)
					world.setTree (16,4,true)
					world.setTree (17,3,true)
					world.setTree (18,3,true)
					world.setTree (3,3,true)
					world.setTree (4,3,true)
					world.setTree (2,1,true)
					world.setTree (4,2,true)
					world.setTree (6,1,true)
					world.setTree (8,2,true)
					world.setTree (10,1,true)
					world.setTree (12,2,true)
					world.setTree (5,3,true)
					world.setTree (6,3,true)
					world.setTree (7,3,true)
					world.setTree (8,3,true)
					world.setTree (9,3,true)
					world.setTree (10,3,true)
					world.setTree (11,3,true)
					world.setTree (12,3,true)
					world.setTree (13,3,true)
					world.setTree (14,3,true)
					world.setTree (15,3,true)
					world.setTree (16,3,true)
					world.setTree (14,1,true)
					world.setTree (16,2,true)
					world.setTree (18,1,true)
					world.setTree (19,1,true)
					world.setTree (19,5,true)
					world.setTree (18,5,true)
					world.setTree (0,7,true)
					world.setTree (0,8,true)
					world.setTree (0,9,true)
					world.setTree (20,9,true)
					world.setTree (20,8,true)
					world.setTree (20,7,true)
					world.setTree (1,9,true)
					world.setTree (2,9,true)
					world.setTree (3,9,true)
					world.setTree (4,9,true)
					world.setTree (5,9,true)
					world.setTree (6,9,true)
					world.setTree (7,9,true)
					world.setTree (8,9,true)
					world.setTree (9,9,true)
					world.setTree (10,9,true)
					world.setTree (11,9,true)
					world.setTree (12,9,true)
					world.setTree (13,9,true)
					world.setTree (14,9,true)
					world.setTree (15,9,true)
					world.setTree (16,9,true)
					world.setTree (17,9,true)
					world.setTree (18,9,true)
					world.setTree (19,9,true)
					world.setTree (10,7,true)
					world.setTree (14,5,true)
					world.setTree (10,5,true)
					world.setTree (6,5,true)
					world.setTree (2,5,true)
					world.setTree (2,7,true)
					world.setTree (4,8,true)
					world.setTree (6,7,true)
					world.setTree (8,8,true)
					world.setTree (12,8,true)
					world.setTree (14,7,true)
					world.setMushroom (18,8,true)
					world.setMushroom (17,7,true)
					world.setLeaf (19,7,true)
				when 11
					world.clearAll
					world.setSize(4,6)
					kara.setPosition(2,1)
					kara.setDirection(1)
                    dir = 1
					world.setTree(1,0,true)
					world.setTree(2,0,true)
					world.setTree(3,0,true)
					world.setTree(0,0,true)
					world.setTree(3,1,true)
					world.setTree(3,2,true)
					world.setTree(2,2,true)
					world.setTree(1,2,true)
					world.setTree(0,2,true)
					world.setTree(0,3,true)
					world.setTree(1,3,true)
					world.setTree(2,3,true)
					world.setTree(3,3,true)
					world.setTree(3,4,true)
					world.setTree(3,5,true)
					world.setTree(0,5,true)
					world.setTree(0,4,true)
					world.setTree(1,5,true)
					world.setTree(2,5,true)
					world.setLeaf(2,4,true)
				when 12
					world.clearAll
					world.setSize(8,6)
					kara.setPosition(2,1)
					kara.setDirection(1)
                    dir = 1
					world.setTree(0,0,true)
					world.setTree(1,0,true)
					world.setTree(2,0,true)
					world.setTree(3,0,true)
					world.setTree(3,2,true)
					world.setTree(1,2,true)
					world.setTree(0,2,true)
					world.setTree(4,0,true)
					world.setTree(4,2,true)
					world.setTree(4,1,true)
					world.setTree(4,3,true)
					world.setTree(4,4,true)
					world.setTree(3,4,true)
					world.setTree(0,4,true)
					world.setTree(0,3,true)
					world.setTree(1,3,true)
					world.setTree(3,3,true)
					world.setTree(2,2,true)
					world.setTree(3,1,true)
					world.setTree(2,3,true)
					world.setTree(5,2,true)
					world.setTree(6,2,true)
					world.setTree(7,2,true)
					world.setTree(7,1,true)
					world.setTree(7,0,true)
					world.setTree(6,0,true)
					world.setTree(7,3,true)
					world.setTree(7,4,true)
					world.setTree(7,5,true)
					world.setTree(6,5,true)
					world.setTree(4,5,true)
					world.setTree(5,3,true)
					world.setTree(6,3,true)
					world.setTree(0,5,true)
					world.setTree(1,5,true)
					world.setTree(2,5,true)
					world.setTree(3,5,true)
					world.setLeaf(2,4,true)
				when 13
					world.clearAll
					world.setSize(5,12)
					kara.setPosition(3,1)
					kara.setDirection(1)
                    dir = 1
					world.setTree(0,0,true)
					world.setTree(1,0,true)
					world.setTree(2,0,true)
					world.setTree(3,0,true)
					world.setTree(3,2,true)
					world.setTree(1,2,true)
					world.setTree(0,2,true)
					world.setTree(4,0,true)
					world.setTree(4,2,true)
					world.setTree(4,1,true)
					world.setTree(4,4,true)
					world.setTree(3,4,true)
					world.setTree(0,4,true)
					world.setTree(0,3,true)
					world.setTree(1,3,true)
					world.setTree(4,5,true)
					world.setTree(0,5,true)
					world.setTree(1,5,true)
					world.setTree(2,5,true)
					world.setTree(3,5,true)
					world.setTree(1,4,true)
					world.setTree(0,1,true)
					world.setTree(0,6,true)
					world.setTree(1,6,true)
					world.setTree(2,6,true)
					world.setTree(3,6,true)
					world.setTree(4,6,true)
					world.setTree(0,7,true)
					world.setTree(0,8,true)
					world.setTree(2,8,true)
					world.setTree(2,9,true)
					world.setTree(1,9,true)
					world.setTree(0,9,true)
					world.setTree(0,10,true)
					world.setTree(0,11,true)
					world.setTree(1,11,true)
					world.setTree(2,11,true)
					world.setTree(3,11,true)
					world.setTree(4,11,true)
					world.setTree(4,10,true)
					world.setTree(4,9,true)
					world.setTree(4,8,true)
					world.setTree(4,7,true)
					world.setMushroom(2,3,true)
					world.setMushroom(2,1,true)
					world.setLeaf(1,8,true)
				when 14
					world.clearAll
					world.setSize(12,12)
					kara.setPosition(2,3)
					kara.setDirection(3)
                    dir = 3
					world.setTree(0,0,true)
					world.setTree(1,0,true)
					world.setTree(2,0,true)
					world.setTree(3,0,true)
					world.setTree(4,0,true)
					world.setTree(5,0,true)
					world.setTree(5,1,true)
					world.setTree(5,2,true)
					world.setTree(5,3,true)
					world.setTree(5,4,true)
					world.setTree(5,5,true)
					world.setTree(4,5,true)
					world.setTree(3,5,true)
					world.setTree(2,5,true)
					world.setTree(1,5,true)
					world.setTree(0,5,true)
					world.setTree(0,3,true)
					world.setTree(0,2,true)
					world.setTree(0,4,true)
					world.setTree(1,2,true)
					world.setTree(2,2,true)
					world.setTree(3,2,true)
					world.setTree(1,3,true)
					world.setTree(1,4,true)
					world.setTree(3,3,true)
					world.setTree(6,0,true)
					world.setTree(8,0,true)
					world.setTree(9,0,true)
					world.setTree(10,0,true)
					world.setTree(11,0,true)
					world.setTree(11,1,true)
					world.setTree(11,2,true)
					world.setTree(11,3,true)
					world.setTree(11,4,true)
					world.setTree(11,5,true)
					world.setTree(10,5,true)
					world.setTree(9,5,true)
					world.setTree(8,5,true)
					world.setTree(7,5,true)
					world.setTree(6,5,true)
					world.setTree(6,4,true)
					world.setTree(6,3,true)
					world.setTree(6,2,true)
					world.setTree(6,1,true)
					world.setTree(7,3,true)
					world.setTree(8,3,true)
					world.setTree(9,3,true)
					world.setTree(9,1,true)
					world.setTree(8,1,true)
					world.setTree(10,1,true)
					world.setTree(0,6,true)
					world.setTree(1,6,true)
					world.setTree(2,6,true)
					world.setTree(3,6,true)
					world.setTree(4,6,true)
					world.setTree(5,6,true)
					world.setTree(5,7,true)
					world.setTree(5,8,true)
					world.setTree(5,9,true)
					world.setTree(5,10,true)
					world.setTree(5,11,true)
					world.setTree(3,11,true)
					world.setTree(2,11,true)
					world.setTree(1,11,true)
					world.setTree(0,11,true)
					world.setTree(0,10,true)
					world.setTree(0,9,true)
					world.setTree(0,8,true)
					world.setTree(0,7,true)
					world.setTree(4,8,true)
					world.setTree(3,8,true)
					world.setTree(2,8,true)
					world.setTree(1,10,true)
					world.setTree(2,10,true)
					world.setTree(3,10,true)
					world.setTree(6,6,true)
					world.setTree(6,7,true)
					world.setTree(6,8,true)
					world.setTree(6,9,true)
					world.setTree(6,10,true)
					world.setTree(6,11,true)
					world.setTree(7,11,true)
					world.setTree(8,11,true)
					world.setTree(9,11,true)
					world.setTree(10,11,true)
					world.setTree(11,11,true)
					world.setTree(11,10,true)
					world.setTree(11,9,true)
					world.setTree(11,8,true)
					world.setTree(11,7,true)
					world.setTree(11,6,true)
					world.setTree(10,6,true)
					world.setTree(9,6,true)
					world.setTree(8,6,true)
					world.setTree(7,6,true)
					world.setTree(10,7,true)
					world.setTree(7,8,true)
					world.setTree(8,8,true)
					world.setTree(7,9,true)
					world.setTree(8,9,true)
					world.setTree(9,9,true)
					world.setLeaf(7,10,true)
				when 15
					world.clearAll
					world.setSize(16,16)
					kara.setPosition(1,1)
					kara.setDirection(2)
                    dir = 2
					world.setTree(0,0,true)
					world.setTree(0,1,true)
					world.setTree(0,2,true)
					world.setTree(0,3,true)
					world.setTree(0,4,true)
					world.setTree(0,5,true)
					world.setTree(0,6,true)
					world.setTree(0,7,true)
					world.setTree(1,7,true)
					world.setTree(2,7,true)
					world.setTree(3,7,true)
					world.setTree(4,7,true)
					world.setTree(5,7,true)
					world.setTree(6,7,true)
					world.setTree(7,7,true)
					world.setTree(8,7,true)
					world.setTree(9,7,true)
					world.setTree(10,7,true)
					world.setTree(11,7,true)
					world.setTree(12,7,true)
					world.setTree(13,7,true)
					world.setTree(14,7,true)
					world.setTree(15,7,true)
					world.setTree(15,5,true)
					world.setTree(15,4,true)
					world.setTree(15,3,true)
					world.setTree(15,2,true)
					world.setTree(15,1,true)
					world.setTree(15,0,true)
					world.setTree(14,0,true)
					world.setTree(13,0,true)
					world.setTree(12,0,true)
					world.setTree(11,0,true)
					world.setTree(10,0,true)
					world.setTree(9,0,true)
					world.setTree(8,0,true)
					world.setTree(7,0,true)
					world.setTree(6,0,true)
					world.setTree(5,0,true)
					world.setTree(4,0,true)
					world.setTree(3,0,true)
					world.setTree(2,0,true)
					world.setTree(1,0,true)
					world.setTree(0,8,true)
					world.setTree(0,9,true)
					world.setTree(0,10,true)
					world.setTree(0,11,true)
					world.setTree(0,12,true)
					world.setTree(0,13,true)
					world.setTree(0,14,true)
					world.setTree(0,15,true)
					world.setTree(1,15,true)
					world.setTree(2,15,true)
					world.setTree(3,15,true)
					world.setTree(4,15,true)
					world.setTree(5,15,true)
					world.setTree(6,15,true)
					world.setTree(7,15,true)
					world.setTree(8,15,true)
					world.setTree(9,15,true)
					world.setTree(10,15,true)
					world.setTree(11,15,true)
					world.setTree(12,15,true)
					world.setTree(13,15,true)
					world.setTree(14,15,true)
					world.setTree(15,15,true)
					world.setTree(15,14,true)
					world.setTree(15,13,true)
					world.setTree(15,12,true)
					world.setTree(15,11,true)
					world.setTree(15,10,true)
					world.setTree(15,9,true)
					world.setTree(15,8,true)
					world.setTree(14,8,true)
					world.setTree(13,8,true)
					world.setTree(12,8,true)
					world.setTree(11,8,true)
					world.setTree(10,8,true)
					world.setTree(9,8,true)
					world.setTree(8,8,true)
					world.setTree(7,8,true)
					world.setTree(6,8,true)
					world.setTree(5,8,true)
					world.setTree(4,8,true)
					world.setTree(3,8,true)
					world.setTree(2,8,true)
					world.setTree(1,8,true)
					world.setTree(2,1,true)
					world.setTree(2,2,true)
					world.setTree(2,3,true)
					world.setTree(2,4,true)
					world.setTree(2,5,true)
					world.setTree(4,5,true)
					world.setTree(4,4,true)
					world.setTree(4,3,true)
					world.setTree(4,2,true)
					world.setTree(4,6,true)
					world.setTree(6,1,true)
					world.setTree(6,2,true)
					world.setTree(6,3,true)
					world.setTree(6,4,true)
					world.setTree(6,5,true)
					world.setTree(8,6,true)
					world.setTree(8,5,true)
					world.setTree(8,4,true)
					world.setTree(8,3,true)
					world.setTree(8,2,true)
					world.setTree(10,1,true)
					world.setTree(10,2,true)
					world.setTree(10,3,true)
					world.setTree(10,4,true)
					world.setTree(10,5,true)
					world.setTree(12,6,true)
					world.setTree(12,5,true)
					world.setTree(12,4,true)
					world.setTree(12,3,true)
					world.setTree(12,2,true)
					world.setTree(14,1,true)
					world.setTree(14,2,true)
					world.setTree(14,3,true)
					world.setTree(14,4,true)
					world.setTree(14,5,true)
					world.setTree(2,9,true)
					world.setTree(2,10,true)
					world.setTree(2,11,true)
					world.setTree(2,12,true)
					world.setTree(2,13,true)
					world.setTree(4,14,true)
					world.setTree(4,13,true)
					world.setTree(4,12,true)
					world.setTree(4,11,true)
					world.setTree(4,9,true)
					world.setTree(5,9,true)
					world.setTree(6,9,true)
					world.setTree(6,10,true)
					world.setTree(6,11,true)
					world.setTree(6,12,true)
					world.setTree(6,14,true)
					world.setTree(3,9,true)
					world.setTree(8,14,true)
					world.setTree(7,14,true)
					world.setTree(9,14,true)
					world.setTree(8,12,true)
					world.setTree(9,12,true)
					world.setTree(9,13,true)
					world.setTree(8,11,true)
					world.setTree(8,9,true)
					world.setTree(9,9,true)
					world.setTree(12,10,true)
					world.setTree(11,9,true)
					world.setTree(10,9,true)
					world.setTree(12,9,true)
					world.setTree(12,11,true)
					world.setTree(11,11,true)
					world.setTree(9,11,true)
					world.setTree(11,14,true)
					world.setTree(11,12,true)
					world.setTree(13,12,true)
					world.setTree(12,12,true)
					world.setTree(13,13,true)
					world.setTree(14,10,true)
					world.setTree(7,9,true)
					world.setMushroom(5,11,true)
					world.setMushroom(6,13,true)
					world.setMushroom(8,10,true)
					world.setMushroom(10,13,true)
					world.setLeaf(14,9,true)
				when 16
					Output(kara,tools,world,app_path,menu,"Du hast alle Level geschaft! Warte bis zum nächsten Update.","","")
					k = 1
			end
			`"#{my_path}"mouse zoomKara`
			if k == 0
				spx = Input(kara,tools,world,app_path,menu,"Gebe Karas Weg an um das Blatt zu fressen","s","","","")
				spx=spx.downcase
				kk = 0
				spx.each_byte do |spy| 
					if kk == 0
						case (spy.chr)
							when "m"
                                if dir == 0 and kara.mushroomFront() and world.isEmpty(kara.getPosition().getX,(kara.getPosition().getY-2))
                                    kara.move
                                elsif dir == 1 and kara.mushroomFront() and world.isEmpty(kara.getPosition().getX-2,(kara.getPosition().getY))
                                    kara.move
                                elsif dir == 2 and kara.mushroomFront() and world.isEmpty(kara.getPosition().getX,(kara.getPosition().getY+2))
                                    kara.move
                                elsif dir == 3 and kara.mushroomFront() and world.isEmpty(kara.getPosition().getX+2,(kara.getPosition().getY))
                                    kara.move
                                elsif not kara.treeFront() and not kara.mushroomFront()
									kara.move
								else
									kk = 1
								end
							when "r"
								kara.turnRight
                                dir = dir-1
                                if dir == -1
                                    dir = 3
                                end
							when "l"
								kara.turnLeft
                                dir = dir+1
                                if dir == 4
                                    dir = 0
                                end
							when "e"
								if not kara.onLeaf
									Output(kara,tools,world,app_path,menu,"Du hast verlohren","","")
								end
								if kara.onLeaf
									kara.removeLeaf
									case sp
										when sp = "1"
											fspi = File.new(my_path + "karas_welt.txt", "w+")
											fspi.puts(weltx + 1)
											fspi.puts(spieler2)
											fspi.puts(spieler3)
											fspi.puts(spieler4)
											fspi.rewind
											fspi.close
											weltx = weltx + 1
										when sp = "2"
											fspi = File.new(my_path + "karas_welt.txt", "w+")
											fspi.puts(spieler1)
											fspi.puts(weltx + 1)
											fspi.puts(spieler3)
											fspi.puts(spieler4)
											fspi.rewind
											fspi.close
											weltx = weltx + 1
										when sp = "3"
											fspi = File.new(my_path + "karas_welt.txt", "w+")
											fspi.puts(spieler1)
											fspi.puts(spieler2)
											fspi.puts(weltx + 1)
											fspi.puts(spieler4)
											fspi.rewind
											fspi.close
											weltx = weltx + 1
										when sp = "4"
											fspi = File.new(my_path + "karas_welt.txt", "w+")
											fspi.puts(spieler1)
											fspi.puts(spieler2)
											fspi.puts(spieler3)
											fspi.puts(weltx + 1)
											fspi.rewind
											fspi.close
											weltx = weltx + 1
									end
								end
								kk = 1
							when "t"
								cox = kara.getPosition.getX
								coy = kara.getPosition.getY 
								if (weltx == 11 and cox == 0 and coy == 1)
									kara.setPosition(1,4)
									kara.setDirection(3)
								end
								if (weltx == 12 and cox == 0 and coy == 1)
									kara.setPosition(6,4)
									kara.setDirection(1)
								end
								if (weltx == 12 and cox == 5 and coy == 5)
									kara.setPosition(6,1)
									kara.setDirection(3)
								end
								if (weltx == 12 and cox == 5 and coy == 0)
									kara.setPosition(1,4)
									kara.setDirection(0)
								end
								if (weltx == 13 and cox == 4 and coy == 3)
									kara.setPosition(1,10)
									kara.setDirection(3)
								end
								if (weltx == 14 and cox == 0 and coy == 1)
									kara.setPosition(7,4)
									kara.setDirection(3)
								end
								if (weltx == 14 and cox == 7 and coy == 0)
									kara.setPosition(4,7)
									kara.setDirection(1)
								end
								if (weltx == 14 and cox == 4 and coy == 11)
									kara.setPosition(7,7)
									kara.setDirection(3)
								end
								if (weltx == 15 and cox == 15 and coy == 6)
									kara.setPosition(1,9)
									kara.setDirection(2)
								end
						end
						tools.sleep (300)
					end
				end
			end
			f = 0
			while f == 0 and k == 0
				re = Input(kara,tools,world,app_path,menu,"wilst du zum nächsten Level oder wenn du es nicht geschaft hast es wiederhohlen?","s","ja/nein","","")
				case re
					when "ja"
						f = 1
					when "nein"
						f = 1
						k = 1
					else
						Output(kara,tools,world,app_path,menu,"bite antworte mit ja/nein","","")
				end 
			end
		end
    end
	Output(kara,tools,world,app_path,menu,"Drücke ok damit das Programm beendet wird","","")
end  